GET http://127.0.0.1:3001/api/blogs HTTP/1.1

###

GET http://127.0.0.1:3001/api/blogs?search=aR HTTP/1.1

###

POST http://127.0.0.1:3001/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9sYWZAc25vdy5tYW4iLCJpZCI6MSwiaWF0IjoxNjc1NDIyODYyfQ.TozRHcdqzyaD57kWr4OR3T1BQ_zkLGfxCtHowShDGPo

{
    "author": "Olaf",
    "url": "https://www.olaf.blog/2013/why-i-love-summer.html",
    "title": "Why I love summer?"
}

###

PUT http://127.0.0.1:3001/api/blogs/4 HTTP/1.1
Content-Type: application/json

{
    "likes": 13
}

###

DELETE http://127.0.0.1:3001/api/blogs/4 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9sYWZAc25vdy5tYW4iLCJpZCI6MSwiaWF0IjoxNjc1NDIyODYyfQ.TozRHcdqzyaD57kWr4OR3T1BQ_zkLGfxCtHowShDGPo
