GET http://127.0.0.1:3001/api/users HTTP/1.1

###

GET http://127.0.0.1:3001/api/users/olaf@snow.man HTTP/1.1

###

POST http://127.0.0.1:3001/api/users HTTP/1.1
Content-Type: application/json

{
    "username": "i-love-summer@olaf.snow",
    "name": "Olaf",
    "password": "Made4Summer"
}

###

PUT http://127.0.0.1:3001/api/users/i-love-summer@olaf.snow HTTP/1.1
Content-Type: application/json

{
    "username": "olaf@snow.man"
}

###

POST http://127.0.0.1:3001/api/users HTTP/1.1
Content-Type: application/json

{
    "username": "elsa@queen.snow",
    "name": "Elsa",
    "password": "LetItGo"
}
