fragment BookDetails on Book {
  title
  author {
    name
  }
  published
  genres
}

mutation error0 {
  addBook(title: "A", author: "Valo", published: 2022, genres: ["fake"]) {
    ...BookDetails
  }
}

mutation error1 {
  addBook(title: "The Book", author: "A", published: 2022, genres: ["fake"]) {
    ...BookDetails
  }
}

mutation error2 {
  createUser(username: "A", favoriteGenre: "fake") {
    username
    favoriteGenre
  }
}
