POST http://localhost:3003/api/blogs/631db588cf20605945871db3/comments
Content-Type: application/json

{
  "comment": "This is a comment"
}

###

POST http://localhost:3003/api/blogs/631db588cf20605945871db3/comments
Content-Type: application/json

{
  "comment": "<script>alert('This is a comment')</script>"
}
