services:
  bloglist-postgres:
    image: postgres:14.5 # The same version as in Dokku
    environment:
      POSTGRES_USER: bloglist_user
      POSTGRES_PASSWORD: bloglist_password
      POSTGRES_DB: bloglist
    volumes:
      - ./commands.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    restart: always
    container_name: fs-bloglist-postgres
